# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'APPMeuTreino' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for APPMeuTreino

  target 'APPMeuTreinoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'APPMeuTreinoUITests' do
    # Pods for testing
  end

pod 'Alamofire'
pod 'YouTubePlayer'

end